# Generated by Django 4.1 on 2022-08-27 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated_at',
            new_name='updated_time',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='created_at',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='updated_at',
            new_name='updated_time',
        ),
    ]
